/*
 * ClassroomJudge.java
 *
 * Created on __DATE__, __TIME__
 */

package UI;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import JDBC.ArrangeImpl;

/**
 *
 * @author  __USER__
 */
public class ClassroomJudge extends javax.swing.JFrame {

	/** Creates new form ClassroomJudge */
	public ClassroomJudge() {
		initComponents();
		this.fillClassRoom();
		setLocation(200, 100);
	}

	private void fillClassRoom() {
		List<String> classroomList = new ArrayList<String>();
		ArrangeImpl ai = new ArrangeImpl();
		classroomList = ai.getClassRoom();
		for (String string : classroomList) {
			this.jComboBox1.addItem(string);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton4 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton6 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u8bfe\u5ba4\u5360\u7528\u5b89\u6392");

		jButton4.setIcon(new javax.swing.ImageIcon(
				"..\\AutomaticCourse\\images\\modify.png")); // NOI18N
		jButton4.setText("\u5f55\u5165");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, "1", "0", "0" },
						{ null, "1", "1", "0" }, { null, "1", "2", "0" },
						{ null, "1", "3", "0" }, { null, "1", "4", "0" },
						{ null, "1", "5", "0" }, { null, "1", "6", "0" },
						{ null, "1", "7", "0" }, { null, "1", "8", "0" },
						{ null, "1", "9", "0" }, { null, "1", "10", "0" },
						{ null, "2", "0", "0" }, { null, "2", "1", "0" },
						{ null, "2", "2", "0" }, { null, "2", "3", "0" },
						{ null, "2", "4", "0" }, { null, "2", "5", "0" },
						{ null, "2", "6", "0" }, { null, "2", "7", "0" },
						{ null, "2", "8", "0" }, { null, "2", "9", "0" },
						{ null, "2", "10", "0" }, { null, "3", "0", "0" },
						{ null, "3", "1", "0" }, { null, "3", "2", "0" },
						{ null, "3", "3", "0" }, { null, "3", "4", "0" },
						{ null, "3", "5", "0" }, { null, "3", "6", "0" },
						{ null, "3", "7", "0" }, { null, "3", "8", "0" },
						{ null, "3", "9", "0" }, { null, "3", "10", "0" },
						{ null, "4", "0", "0" }, { null, "4", "1", "0" },
						{ null, "4", "2", "0" }, { null, "4", "3", "0" },
						{ null, "4", "4", "0" }, { null, "4", "5", "0" },
						{ null, "4", "6", "0" }, { null, "4", "7", "0" },
						{ null, "4", "8", "0" }, { null, "4", "9", "0" },
						{ null, "4", "10", "0" }, { null, "5", "0", "0" },
						{ null, "5", "1", "0" }, { null, "5", "2", "0" },
						{ null, "5", "3", "0" }, { null, "5", "4", "0" },
						{ null, "5", "5", "0" }, { null, "5", "6", "0" },
						{ null, "5", "7", "0" }, { null, "5", "8", "0" },
						{ null, "5", "9", "0" }, { null, "5", "10", "0" } },
				new String[] { "课室地点", "星期数(周几)", "节数(第几节)", "是否占用(置1占用)" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { true, false, false, true };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setText("\u8bfe\u5ba4\u5730\u70b9\uff1a");

		jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 24));
		jLabel3.setText("\u8bfe\u5ba4\u5360\u7528\u5b89\u6392");

		jButton6.setIcon(new javax.swing.ImageIcon(
				"..\\AutomaticCourse\\images\\add.png")); // NOI18N
		jButton6.setText("\u6dfb\u52a0");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton5.setIcon(new javax.swing.ImageIcon(
				"..\\AutomaticCourse\\images\\exit.png")); // NOI18N
		jButton5.setText("\u8fd4\u56de");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton7.setIcon(new javax.swing.ImageIcon(
				"..\\AutomaticCourse\\images\\reset.png")); // NOI18N
		jButton7.setText("\u91cd\u7f6e");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		570,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(19, 19,
																		19)
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jComboBox1,
																		0,
																		372,
																		Short.MAX_VALUE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton6,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		108,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jButton7,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										108,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										354,
																										Short.MAX_VALUE)
																								.addComponent(
																										jButton4,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										108,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						jButton5,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						108,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(231, Short.MAX_VALUE)
								.addComponent(jLabel3).addGap(219, 219, 219)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(26, 26, 26)
								.addComponent(jLabel3)
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jButton6)
												.addComponent(
														jComboBox1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										290,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton4)
												.addComponent(jButton7))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										22, Short.MAX_VALUE)
								.addComponent(jButton5).addGap(30, 30, 30)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		ArrangeImpl ai = new ArrangeImpl();
		try {
			for (int i = 0; i < 55; i++) {
				String classroomjudge[] = { (String) jTable1.getValueAt(i, 0),
						(String) jTable1.getValueAt(i, 1),
						(String) jTable1.getValueAt(i, 2),
						(String) jTable1.getValueAt(i, 3) };
				if (!ai.insertClassroomJudge(classroomjudge)) {
					System.out.println("条目" + i + ", 插入失败!!!");
				}
			}
			JOptionPane.showMessageDialog(null,
					"        		插入成功!!!                    ",
					"AutoCourseArrangement", JOptionPane.PLAIN_MESSAGE);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null,
					"        		插入失败!!!                    ",
					"AutoCourseArrangement", JOptionPane.PLAIN_MESSAGE);
		}
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose(); //退出界面
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			for (int i = 0; i < 55; i++) { //清空row = 0
				jTable1.setValueAt(null, i, 0);
				jTable1.setValueAt(0, i, 3);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String classroomPlace = (String) jComboBox1.getSelectedItem();
		for (int i = 0; i < 55; i++) {
			jTable1.setValueAt(classroomPlace, i, 0);
		}

	}

	/**
	 * @param args the command line arguments
	 */
	//	public static void main(String args[]) {
	//		java.awt.EventQueue.invokeLater(new Runnable() {
	//			public void run() {
	//				new ClassroomJudge().setVisible(true);
	//			}
	//		});
	//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}